---
- name: Sync OpenStack lab into NetBox
  hosts: localhost
  gather_facts: no

  vars:
    netbox_url: "http://10.20.20.21:8080"
    netbox_token: "YOUR_WORKING_TOKEN"

  tasks:

    - name: Create HomeLab site
      uri:
        url: "{{ netbox_url }}/api/dcim/sites/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: HomeLab
          slug: homelab
        status_code: [201,400]

    - name: Create openstack device
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: openstack
          site: HomeLab
          status: active
        status_code: [201,400]

    - name: Create openstack-lab2 device
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: openstack-lab2
          site: HomeLab
          status: active
        status_code: [201,400]

    - name: Create openstack management IP
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          address: "192.168.1.176/24"
          status: active
        status_code: [201,400]

    - name: Create openstack-lab2 management IP
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          address: "192.168.1.178/24"
          status: active
        status_code: [201,400]
