---
- name: Sync OpenStack lab into NetBox
  hosts: localhost
  gather_facts: no

  vars:
    netbox_url: "http://10.20.20.21:8080"
    netbox_token: "nbt_xtSHREV88CqJ.YibtGGdeAzWlbqlFsjJVuYWkmJsX1MA1qk1JBTZX"

    lab_devices:
      - name: Cloud2-AWX-Console
        site: Cloud2
        ip: 10.20.20.211/24
      - name: Cloud2-AWX-APP
        site: Cloud2
        ip: 10.20.20.7/24
      - name: Cloud2-Jumpstation
        site: Cloud2
        ip: 10.20.20.53/24
      - name: Jumpstation-Ubuntu
        site: Cloud1
        ip: 10.10.10.199/24

    openstack_interfaces:
      - br-ex
      - br-int
      - gre-cloud1

    openstack_lab2_interfaces:
      - br-ex
      - br-int
      - gre-cloud2

  tasks:
    - name: Create lab VM devices
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ item.name }}"
          site: "{{ item.site }}"
          status: active
        status_code: [201, 400]
      loop: "{{ lab_devices }}"

    - name: Create lab VM IP addresses
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          address: "{{ item.ip }}"
          status: active
        status_code: [201, 400]
      loop: "{{ lab_devices }}"

    - name: Create interfaces for openstack
      uri:
        url: "{{ netbox_url }}/api/dcim/interfaces/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          device: 4
          name: "{{ item }}"
          type: virtual
          enabled: true
        status_code: [201, 400]
      loop: "{{ openstack_interfaces }}"

    - name: Create interfaces for openstack-lab2
      uri:
        url: "{{ netbox_url }}/api/dcim/interfaces/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          device: 5
          name: "{{ item }}"
          type: virtual
          enabled: true
        status_code: [201, 400]
      loop: "{{ openstack_lab2_interfaces }}"
