---
- name: Update NetBox
  hosts: localhost
  gather_facts: false

  vars:
    netbox_url: "http://10.20.20.21:8080"
    netbox_token: "nbt_xtSHREV88CqJ.YibtGGdeAzWlbqlFsjJVuYWkmJsX1MA1qk1JBTZX"

  tasks:
    - name: Test NetBox API
      uri:
        url: "{{ netbox_url }}/api/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: result

    - debug:
        var: result.status
